name: demo
on:
pull_request:
push: 
  branches
  master
  develop
jobs:
test:
  name: running Units tests
  runs-on: linux-latest
steps:
  uses: action/checkout@v1
  name: Use Node.js ${{matrix.node-version }}
uses: actions/setup-npde@v1
with:
  node-version: ${{matrix.node-version }}
  name: install
  run: npm install
