name: demo
on:
pull_request:
push:
 branches
 - master
 - develop
 jobs:
 test:
   name: running Units tests
  - runs-on: linux-latest
  steps:
  - uses: action/checkout@v1
  - name: Use Node.js ${{matrix.node-version }}
  uses: actions/setup-npde@v1
  with:
   node-version: ${{matrix.node-version }}
   - name: install
   run: npm install
   - name: test
   run: npm test
   
   - name: Download a Build Artifact
  uses: actions/download-artifact@v3.0.2
  with:
    # Artifact name
    name: # optional
    # Destination path
    path: # optional
 
 
  
